###  GYM
image black_girl_changing1 = "interactions/gym/black_girl_changing1.jpg"
image black_girl_changing2 = "interactions/gym/black_girl_changing2.jpg"
image black_girl_changing3 = "interactions/gym/black_girl_changing3.jpg"
image blonde_rubbing_locker1 = "interactions/gym/blonde_rubbing_locker1.jpg"
image blonde_rubbing_locker2 = "interactions/gym/blonde_rubbing_locker2.jpg"
image blonde_rubbing_locker3 = "interactions/gym/blonde_rubbing_locker3.jpg"
image blonde_rubbing_locker4 = "interactions/gym/blonde_rubbing_locker4.jpg"
image fattie_swimming1 = "interactions/gym/fattie_swimming1.jpg"
image fattie_swimming2 = "interactions/gym/fattie_swimming2.jpg"
image fattie_swimming3 = "interactions/gym/fattie_swimming3.jpg"
image fattie_treadmill1 = "interactions/gym/gym_fattie_treadmill1.jpg"
image fattie_treadmill2 = "interactions/gym/gym_fattie_treadmill2.jpg"
image fattie_treadmill3 = "interactions/gym/gym_fattie_treadmill3.jpg"
image fattie_treadmill4 = "interactions/gym/gym_fattie_treadmill4.jpg"
image fattie_treadmill5 = "interactions/gym/gym_fattie_treadmill5.jpg"
image fattie_locker_attack1 = "interactions/gym/fattie_locker_attack1.jpg"
image fattie_locker_attack2 = "interactions/gym/fattie_locker_attack2.jpg"
image fattie_locker_attack3 = "interactions/gym/fattie_locker_attack3.jpg"
image fattie_locker_attack4 = "interactions/gym/fattie_locker_attack4.jpg"
image fattie_locker_attack5 = "interactions/gym/fattie_locker_attack5.jpg"
image fattie_locker_attack6 = "interactions/gym/fattie_locker_attack6.jpg"
image fattie_locker_attack7 = "interactions/gym/fattie_locker_attack7.jpg"
image saggy_tits_latina_sauna1 = "interactions/gym/saggy_tits_latina_sauna1.jpg"
image saggy_tits_latina_sauna2 = "interactions/gym/saggy_tits_latina_sauna2.jpg"
image saggy_tits_latina_sauna3 = "interactions/gym/saggy_tits_latina_sauna3.jpg"
image saggy_tits_latina_sauna4 = "interactions/gym/saggy_tits_latina_sauna4.jpg"
image saggy_tits_latina_sauna5 = "interactions/gym/saggy_tits_latina_sauna5.jpg"
image yoga_2girls1 = "interactions/gym/yoga_2girls1.jpg"
image yoga_2girls2 = "interactions/gym/yoga_2girls2.jpg"
image yoga_2girls3 = "interactions/gym/yoga_2girls3.jpg"
image monica_locker_rub1 = "interactions/gym/monica_domingues_locker_rub1.jpg"
image monica_locker_rub2 = "interactions/gym/monica_domingues_locker_rub2.jpg"
image monica_locker_rub3 = "interactions/gym/monica_domingues_locker_rub3.jpg"
image monica_locker_rub4 = "interactions/gym/monica_domingues_locker_rub4.jpg"
image monica_locker_rub5 = "interactions/gym/monica_domingues_locker_rub5.jpg"
image monica_locker_rub6 = "interactions/gym/monica_domingues_locker_rub6.jpg"
### COFFEE
image mayan_ruclark1 = "interactions/coffee/mayan_ruclark1.jpg"
image mayan_ruclark2 = "interactions/coffee/mayan_ruclark2.jpg"
image mayan_ruclark3 = "interactions/coffee/mayan_ruclark3.jpg"
image mayan_ruclark4 = "interactions/coffee/mayan_ruclark4.jpg"

### ARCADE
image arcade_guy_bored_girl1 = "interactions/arcade/arcade_guy_bored_girl.jpg"
image arcade_guy_bored_girl2 = "interactions/arcade/arcade_guy_bored_girl2.jpg"
image arcade_guy_bored_girl3 = "interactions/arcade/arcade_guy_bored_girl3.jpg"
image arcade_guy_bored_girl4 = "interactions/arcade/arcade_guy_bored_girl4.jpg"
image arcade_guy_bored_girl5 = "interactions/arcade/arcade_guy_bored_girl5.jpg"
image arcade_guy_bored_girl6 = "interactions/arcade/arcade_guy_bored_girl6.jpg"
image arcade_guy_bored_girl7 = "interactions/arcade/arcade_guy_bored_girl7.jpg"
image arcade_guy_bored_girl8 = "interactions/arcade/arcade_guy_bored_girl8.jpg"
image arcade_schoolgirl_hockey_1 = "interactions/arcade/arcade_schoolgirl_hockey_1.jpg"
image arcade_schoolgirl_hockey_2 = "interactions/arcade/arcade_schoolgirl_hockey_2.jpg"
image arcade_schoolgirl_hockey_3 = "interactions/arcade/arcade_schoolgirl_hockey_3.jpg"

### STRIP CLUB
image stripper_brunette = "interactions/strip_club/stripper_brunette.jpg"
image stripper_ginger1 = "interactions/strip_club/stripper_ginger1.jpg"
image stripper_ginger2 = "interactions/strip_club/stripper_ginger2.jpg"
image stripper_ginger3 = "interactions/strip_club/stripper_ginger3.jpg"
image stripper_ginger4 = "interactions/strip_club/stripper_ginger4.jpg"
image stripper_ginger5 = "interactions/strip_club/stripper_ginger5.jpg"
image stripper_ginger6 = "interactions/strip_club/stripper_ginger6.jpg"
